logging:
  pattern:
    console: "%msg%n"
spring:
  application:
    name: Heb
  datasource:
    url: jdbc:mysql://localhost:3306/hebdb?createDatabaseIfNotExist=true
    username: ${MYSQL_SUPER_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
stripe:
    apiUrl: https://api.stripe.com
    enabled: true
    timeout: 1000
    supported-currencies: USD,EUR,GBP
payment-gateway: paypal
mail:
  host: https://localhost.com
  port: 1234
