spring:
  application:
    name: Heb
  datasource:
    url: jdbc:mysql://localhost:3306/hebdb?createDatabaseIfNotExist=true
    username: hebdev
    password: hebdevpassword
stripe:
    apiUrl: https://api.stripe.com
    enabled: true
    timeout: 1000
    supported-currencies: USD,EUR,GBP
payment-gateway: paypal
mail:
  host: https://localhost.com
  port: 1234
